name: Deploy Production

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24.11.1
          cache: "npm"

      - name: Create .env file
        run: |
          printf "%s" "${{ secrets.ENV_PRODUCTION }}" > .env

      - run: npm install --force
      - run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST_PRODUCTION }}
          username: ${{ secrets.USERNAME_PRODUCTION }}
          password: ${{ secrets.PASSWORD_PRODUCTION }}
          port: ${{ secrets.PORT_PRODUCTION }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh

            cd ~/nextjs-restaurant-qr-code
            git fetch --all
            git reset --hard origin/main

            printf "%s" "${{ secrets.ENV_PRODUCTION }}" > .env

            npm i --force
            npm run build
            pm2 restart Nextjs
            pm2 save

  notify:
    name: Telegram Notify
    runs-on: ubuntu-latest
    needs: [build, deploy]
    if: always()
    steps:
      - name: Telegram Success
        if: needs.build.result == 'success' && needs.deploy.result == 'success'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            âœ… DEPLOY NEXTJS QR RESTAURANT SUCCESSFULLY

            ğŸ‘¤ Actor: ${{ github.actor }}
            ğŸ§¾ Commit: ${{ github.event.commits[0].message }}
            ğŸ“¦ Repo: ${{ github.repository }}

            ğŸ”— Commit:
            https://github.com/${{ github.repository }}/commit/${{ github.sha }}

      - name: Telegram Failure
        if: needs.build.result == 'failure' || needs.deploy.result == 'failure'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            âŒ DEPLOY NEXTJS FAILED

            ğŸ‘¤ Actor: ${{ github.actor }}
            ğŸ§¾ Commit: ${{ github.event.commits[0].message }}
            ğŸ“¦ Repo: ${{ github.repository }}

            ğŸ”— Logs:
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
